name: Docker Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: phabricator
      run: docker build ./Dockerfile
    - name: daemon
      run: docker build ./Dockerfile.daemon
    - name: aphlict
      run: docker build ./Dockerfile.aphlict
